env:
  mode: coupled
  dt: 1.0
  frame_stack: 1
  obs_scales: {dr: 5000.0, dv: 0.1, da: 100.0, e: 0.01, theta_deg: 20.0, omega: 0.1}
  action_type: angles_thrust
  gate_thrust_in_eclipse: true
  eta_limit_rad: 0.5235987756  # pi/6
  thrust_max_N: 0.05
  per_orbit_steps: 1            # 1 action per orbit via Shuttlecock adaptor
  episode_orbits: 10            # 10 orbits per episode
  min_perigee_km: 180
  max_att_err_deg: 60

reward_weights:
  w_a: 1.0
  w_e: 0.5
  w_dr: 0.2
  w_dv: 0.2
  w_theta: 1.2
  w_omega: 0.3
  w_h: 0.1
  w_dv_cmd: 0.02     # penalize thrust usage
  w_power: 0.0
  w_jerk: 0.01
  # Note: goal/fail bonuses removed per request

