env:
  mode: coupled
  dt: 1.0
  frame_stack: 1
  action_type: angles_thrust       # Use Shuttlecock adaptor with eta1, eta2, thrust
  # One decision per orbit
  per_orbit_steps: 1
  # Controls (match C-side limits)
  eta_limit_rad: 1.91986217719     # 110 deg in radians
  thrust_max_N: 0.05               # typical max thrust
  gate_thrust_in_eclipse: true

  # Observation scaling (kept simple/default-like)
  obs_scales: {dr: 5000.0, dv: 0.1, da: 100.0, e: 0.01, theta_deg: 20.0, omega: 0.1}

# Reward weights (simple defaults; adjust as needed)
reward_weights:
  w_a: 1.0
  w_e: 0.5
  w_dr: 0.2
  w_dv: 0.2
  w_theta: 1.0
  w_omega: 0.3
  w_h: 0.1
  w_dv_cmd: 0.02
  w_power: 0.0
  w_jerk: 0.01

# Training hyperparameters and rollout cadence
training:
  num_envs: 4
  # Per-episode timing (10 orbits, 1 step/orbit)
  episode_orbits: 10
  steps_per_orbit: 1
  # Update after N episodes per env (rollout length = episode_steps * N)
  update_every_episodes: 5
  n_epochs: 10
  learning_rate: 0.0001
  total_steps: 40000              # ~200 updates with the above settings
  tb_logdir: runs/tb

